source :rubygems

gem 'rails', '3.2.1'
gem 'unicorn', '4.2.0'
gem 'payroll_core', :path => "../core"

group :test do
  gem 'rspec-rails', '2.8.1'
  gem 'in_memory', :path => '../data_store/in_memory'
end
